#  Makefile for Makeing a Library

#which memory model and processor to use by default
PROCESSOR = 386 # for the 32-bit compilers

# name the compiler
CC = wcc$(PROCESSOR)
FC = wfc$(PROCESSOR)
ASM = tasm

!ifeq PROCESSOR 386
MODEL = f       # flat
!else
MODEL = l       # large
!endif

# options to use
#CFLAGS = -m$(MODEL) -zq -od -d2 -zp4 -ei -W4
CFLAGS  = -m$(MODEL) -zq -s -oxt -zp4 -ei -W4
#CFLAGS = -m$(MODEL) -zq -od -s -zp4 -ei -W4
FFLAGS  = -m$(MODEL) -noterm
AFLAGS  = -mx -ml

.EXTENSIONS:
.EXTENSIONS: .exe .rex .lib .obj .wbj .asm .c .for

.BEFORE
	@set INCLUDE=..\apodmx;.;$(%watcom)\h;
	@set LIB=$(%watcom)\lib386;$(%lib)
	@set DOS4G=QUIET

!include objdef.mif

# explicit rules

all :   gfx.lib .symbolic
	@%null

gfx.lib : $(objs)
	 %make temp.lnk
	 wlib $^@ /n /b @temp.lnk

# implicit rules

temp.lnk : objdef.mif makefile
	%create $^@
	for %i in ($(objs)) do %append $^@ -+%i

.c.obj :
	$(CC) $^& $(CFLAGS)

.c.wbj :
	$(CC) $^& $(CFLAGS) -zw -fo=$^&.wbj

.for.obj :
	$(FC) $^& $(FFLAGS)

.asm.obj :
	$(ASM) $(AFLAGS) $^&;

# clean build DIR

clean : .SYMBOLIC
        del *.obj
        del *.lib
