// ASK.INC defines

#define ASK_WINDOW             0x0002  // WINDOW

#define ASK_0000               0x0000  // BUMPIN
#define ASK_0001               0x0001  // BUMPOUT
#define ASK_0002               0x0002  // BUMPOUT
#define ASK_0003               0x0003  // BUMPOUT
#define ASK_0004               0x0004  // BUMPOUT
#define ASK_DRAGBAR            0x0005  // DRAGBAR
#define ASK_YES                0x0006  // BUTTON FIELD
#define ASK_NO                 0x0007  // BUTTON FIELD
