// HELPWIN.INC defines

#define HELP_WINDOW            0x0000  // WINDOW

#define HELP_0000              0x0000  // BUMPIN
#define HELP_0001              0x0001  // BUMPIN
#define HELP_0002              0x0002  // BUMPOUT
#define HELP_0003              0x0003  // BUMPOUT
#define HELP_0004              0x0004  // ICON
#define HELP_UP                0x0005  // BUTTON FIELD
#define HELP_DOWN              0x0006  // BUTTON FIELD
#define HELP_DONE              0x0007  // BUTTON FIELD
#define HELP_TEXT              0x0008  // TEXT FIELD
#define HELP_HEADER            0x0009  // TEXT FIELD
#define HELP_000A              0x000a  // TEXT FIELD
