// LOAD.INC defines

#define LOAD_WINDOW            0x0000  // WINDOW

#define LOAD_0000              0x0000  // BUMPIN
#define LOAD_IDPIC             0x0001  // ICON
#define LOAD_NEXT              0x0002  // BUTTON FIELD
#define LOAD_PREV              0x0003  // BUTTON FIELD
#define LOAD_DEL               0x0004  // BUTTON FIELD
#define LOAD_LOAD              0x0005  // BUTTON FIELD
#define LOAD_CANCEL            0x0006  // BUTTON FIELD
#define LOAD_0007              0x0007  // TEXT FIELD
#define LOAD_0008              0x0008  // TEXT FIELD
#define LOAD_NAME              0x0009  // TEXT FIELD
#define LOAD_CALL              0x000a  // TEXT FIELD
#define LOAD_000B              0x000b  // TEXT FIELD
#define LOAD_CREDITS           0x000c  // TEXT FIELD
