// LOADCOMP.INC defines

#define LCOMP_WINDOW           0x0000  // WINDOW

#define LCOMP_LITE1            0x0000  // ICON
#define LCOMP_LITE2            0x0001  // ICON
#define LCOMP_LITE3            0x0002  // ICON
#define LCOMP_SCREEN           0x0003  // ICON
#define LCOMP_CLOSE            0x0004  // CLOSE GADGET
#define LCOMP_SECRET           0x0005  // BUTTON FIELD
#define LCOMP_B1               0x0006  // BUTTON FIELD
#define LCOMP_B2               0x0007  // BUTTON FIELD
#define LCOMP_B3               0x0008  // BUTTON FIELD
#define LCOMP_SECTOR           0x0009  // TEXT FIELD
#define LCOMP_WAVE             0x000a  // TEXT FIELD
#define LCOMP_LEVEL            0x000b  // VIEW AREA
