// MAIN.INC defines

#define MAIN_WINDOW            0x0000  // WINDOW

#define MAIN_0000              0x0000  // ICON
#define MAIN_NEW               0x0001  // BUTTON FIELD
#define MAIN_LOAD              0x0002  // BUTTON FIELD
#define MAIN_OPTS              0x0003  // BUTTON FIELD
#define MAIN_ORDER             0x0004  // BUTTON FIELD
#define MAIN_CREDITS           0x0005  // BUTTON FIELD
#define MAIN_QUIT              0x0006  // BUTTON FIELD
#define MAIN_RETURN            0x0007  // BUTTON FIELD
#define MAIN_DEMO              0x0008  // TEXT FIELD
#define MAIN_0009              0x0009  // TEXT FIELD
