// OKREG.INC defines

#define OKREG_WINDOW           0x0002  // WINDOW

#define OKREG_0000             0x0000  // BUMPIN
#define OKREG_0001             0x0001  // BUMPIN
#define OKREG_0002             0x0002  // ICON
#define OKREG_0003             0x0003  // ICON
#define OKREG_0004             0x0004  // ICON
#define OKREG_0005             0x0005  // ICON
#define OKREG_TRAIN            0x0006  // BUTTON FIELD
#define OKREG_EASY             0x0007  // BUTTON FIELD
#define OKREG_MED              0x0008  // BUTTON FIELD
#define OKREG_HARD             0x0009  // BUTTON FIELD
#define OKREG_ABORT            0x000a  // BUTTON FIELD
#define OKREG_000B             0x000b  // TEXT FIELD
