// OPTS.INC defines

#define OPTS_WINDOW            0x0002  // WINDOW

#define OPTS_0000              0x0000  // BUMPIN
#define OPTS_0001              0x0001  // BUMPIN
#define OPTS_0002              0x0002  // BUMPIN
#define OPTS_PIC1              0x0003  // ICON
#define OPTS_PIC2              0x0004  // ICON
#define OPTS_PIC3              0x0005  // ICON
#define OPTS_DETAIL            0x0006  // BUTTON FIELD
#define OPTS_EXIT              0x0007  // BUTTON FIELD
#define OPTS_0008              0x0008  // TEXT FIELD
#define OPTS_0009              0x0009  // TEXT FIELD
#define OPTS_000A              0x000a  // TEXT FIELD
#define OPTS_VMUSIC            0x000b  // VIEW AREA
#define OPTS_VFX               0x000c  // VIEW AREA
