// ORDER.INC defines

#define _WINDOW                0x0000  // WINDOW

#define _0000                  0x0000  // ICON
#define _0001                  0x0001  // ICON
#define _0002                  0x0002  // ICON
#define _0003                  0x0003  // ICON
#define _0004                  0x0004  // ICON
#define _0005                  0x0005  // ICON
#define _0006                  0x0006  // TEXT FIELD
