#ifndef _TYPES_H
#include "types.h"
#endif
  
#include "exitapi.h"
#include "gfxapi.h"
#include "ptrapi.h"
#include "kbdapi.h"
#include "glbapi.h"
#include "swdapi.h"
#include "tsmapi.h"
#include "imsapi.h"
#include "vmemapi.h"

#define MAX_SHIELD 100
#define MAX_SUPER  100

#ifndef _FLAMES_H
#include "flame.h"
#endif
  
#ifndef _INTRO_H
#include "intro.h"
#endif

#ifndef _MAPHEADER
#include "map.h"
#endif

#ifndef _FXAPI
#include "fx.h"
#endif

#ifndef _PUBLIC
#include "public.h"
#endif
  
#ifdef DMX_FLAG
#include "dmx.h"
#endif
  
#ifndef _ENEMY
#include "enemy.h"
#endif
  
#ifndef _SHADOWS
#include "shadows.h"
#endif
  
#ifndef _TILEAPI
#include "tile.h"
#endif
  
#ifndef _OBJAPI
#include "objects.h"
#endif
  
#ifndef _BONUSAPI
#include "bonus.h"
#endif
  
#ifndef _STOREAPI
#include "store.h"
#endif
  
#ifndef _ANIMAPI
#include "anims.h"
#endif

#ifndef _SHOTSAPI
#include "shots.h"
#endif

#ifndef _ESHOTAPI
#include "eshot.h"
#endif
  
#ifndef _MOVIE
#include "movie.h"
#endif
  
#ifndef _INPUT_H
#include "input.h"
#endif

#ifndef _LOADSAVE_H
#include "loadsave.h"
#endif

#ifndef _HELP_H
#include "help.h"
#endif

#ifndef _WINDOW_H
#include "windows.h"
#endif
  
