// REGIST.INC defines

#define REG_WINDOW             0x0000  // WINDOW

#define REG_IDPIC              0x0000  // ICON
#define REG_NAME               0x0001  // INPUT FIELD
#define REG_CALLSIGN           0x0002  // INPUT FIELD
#define REG_TEXT               0x0003  // TEXT FIELD
#define REG_VIEWEXIT           0x0004  // VIEW AREA
#define REG_VIEWID             0x0005  // VIEW AREA
#define REG_VIEWREG            0x0006  // VIEW AREA
