// SHIPCOMP.INC defines

#define COMP_WINDOW            0x0000  // WINDOW

#define COMP_LITE1             0x0000  // ICON
#define COMP_LITE2             0x0001  // ICON
#define COMP_LITE3             0x0002  // ICON
#define COMP_CLOSE             0x0003  // CLOSE GADGET
#define COMP_GAME1             0x0004  // BUTTON FIELD
#define COMP_GAME2             0x0005  // BUTTON FIELD
#define COMP_SECRET            0x0006  // BUTTON FIELD
#define COMP_B1                0x0007  // BUTTON FIELD
#define COMP_B2                0x0008  // BUTTON FIELD
#define COMP_B3                0x0009  // BUTTON FIELD
#define COMP_GAME3             0x000a  // BUTTON FIELD
#define COMP_AUTO              0x000b  // BUTTON FIELD
