// STORE.INC defines

#define STOR_WINDOW            0x0000  // WINDOW
#define STOR_ID                0x0000  // ICON
#define STOR_CALLSIGN          0x0001  // DRAGBAR
#define STOR_PREV              0x0002  // BUTTON FIELD
#define STOR_NEXT              0x0003  // BUTTON FIELD
#define STOR_BUY               0x0004  // BUTTON FIELD
#define STOR_BUYIT             0x0005  // BUTTON FIELD
#define STOR_SELL              0x0006  // BUTTON FIELD
#define STOR_COMP              0x0007  // TEXT FIELD
#define STOR_TEXT              0x0008  // TEXT FIELD
#define STOR_COST              0x0009  // TEXT FIELD
#define STOR_SCORE             0x000a  // TEXT FIELD
#define STOR_STATS             0x000b  // TEXT FIELD
#define STOR_TEXTCOST          0x000c  // TEXT FIELD
#define STOR_NUM               0x000d  // TEXT FIELD
#define STOR_VBUY              0x000e  // VIEW AREA
#define STOR_VPREV             0x000f  // VIEW AREA
#define STOR_VNEXT             0x0010  // VIEW AREA
#define STOR_VSCREEN           0x0011  // VIEW AREA
#define STOR_VACCEPT           0x0012  // VIEW AREA
#define STOR_VSELL             0x0013  // VIEW AREA
#define STOR_VEXIT             0x0014  // VIEW AREA
